[config]
run_name = "lighttable_test"

[output]
path = "./output"
file_csv_append = "_output.csv"
file_db_append = "_output.sqlite"

[images]
path = "/home/mop/data/UBC/t20-t40"
crop_left = "10"
crop_right = "10"
crop_top = "15"
crop_bottom = "15"
file_background = "/home/mop/data/UBC/background_crop.tif"
file_calibration = "/home/mop/data/UBC/calibration_crop.tif"
crop_background_and_calibration = false

[camera]
framerate = 24

[linking_weight]
distance = 0.5
area = 0.5
eccentricity = 0.1

[cost_parameters]
max_cost = 300
max_frames = 3
binary_threshold = 180

[sediment]
density = 0.0016

[debugging]
debug = true
stop_time_sec = "2"
